name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main  # Change to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | \
          docker login --username AWS --password-stdin 061747058342.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names name || \
          aws ecr create-repository --repository-name name

      - name: Build, tag, and push Docker image
        env:
          IMAGE_NAME: product
          IMAGE_TAG: latest
          ECR_URI: 061747058342.dkr.ecr.ap-southeast-1.amazonaws.com/name
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:$IMAGE_TAG

      - name: Deploy to ECS
        run: |
          
          CLUSTER_NAME=slit
          CONTAINER_NAME=catalog
          REGION=ap-southeast-1
          IMAGE_URI=061747058342.dkr.ecr.ap-southeast-1.amazonaws.com/name:latest

          # Get current task definition
          TASK_DEF=$(aws ecs describe-task-definition --task-definition $FAMILY_NAME)

          # Create new task definition with updated image
          NEW_TASK_DEF=$(echo $TASK_DEF | \
            jq --arg IMAGE "$IMAGE_URI" --arg CONTAINER "$CONTAINER_NAME" \
            '.taskDefinition | {
              family: .family,
              executionRoleArn: .executionRoleArn,
              networkMode: .networkMode,
              containerDefinitions: [.containerDefinitions[] | 
                if .name == $CONTAINER then .image = $IMAGE else . end],
              requiresCompatibilities: .requiresCompatibilities,
              cpu: .cpu,
              memory: .memory
            }')

          # Register new task definition
          NEW_REVISION=$(echo "$NEW_TASK_DEF" | aws ecs register-task-definition --cli-input-json file:///dev/stdin | jq -r '.taskDefinition.taskDefinitionArn')

          # Update ECS service to use new task definition
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $NEW_REVISION
