name: Docker CI/CD pipeline

on:
  push:
    branches:
      -main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/chekout@v2
        
      - name: Login to Docer Hub
        uses: docker /login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build and push Docker image
        uses: docker/build-push0action@v2
        with:
          context: .
          push: true
          tags: swaraj1sys/docker1:${{github.sha}}

      - name: Deploy to EC2 instance
        uses: applyboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script:
            docker stop docker1 || true
            docker rm docker1 || true
            docker pull ${{secrets.DOCKER_USERNAME}}/docker1:${{github.sha}}
            docker run -d --name docker1 -p 80:80 ${{secrets.DOCKER_USERNAME}}/docker1:${{github.sha}}
            
          
